### ISSUE TITLE
 Error: While trying to resolve module `@inplayer-org/inplayer.js`

### ISSUE THREAD

**Issue by josiahking** [inplayer-org/inplayer.js#561]
## EXPECTED BEHAVIOR

Used be able to use the SDK in reactnative app.

## ACTUAL BEHAVIOR

CONSOLE ERROR:

error: Error: While trying to resolve module `@inplayer-org/inplayer.js` from file `..\src\screens\Login\Login.js`, the package `..\node_modules\@inplayer-org\inplayer.js\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`..\node_modules\@inplayer-org\inplayer.js\dist\inplayer.min.js`. Indeed, none of these files exist:

  * ..\node_modules\@inplayer-org\inplayer.js\dist\inplayer.min.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * ..\node_modules\@inplayer-org\inplayer.js\dist\inplayer.min.js\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (..\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (..\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (..\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at ..\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (..\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at ..\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (..\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
    at _next (..\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)

## STEPS TO REPRODUCE

Installed the package using npm via git url

**Comment by srdjanRakic** [comment]
Hello @josiahking, 

We have double checked on our end and cannot reproduce the issue that was reported. We have successfully created a react-native app. as well as a regular JS/React app. using the library and can confirm it works. In addition, this is the library being used in our paywall application, so we would have noticed an issue.

Based on all this, we assume that the issue might be related with your machine.

Here are some working CodeSandbox examples with React and React Native:
- [REACT](https://codesandbox.io/s/inplayer-react-js-sdk-yf956?file=/src/App.js)
- [REACT-NATIVE](https://codesandbox.io/s/inplayer-react-native-js-sdk-bvhwz?file=/src/App.js)

Kind regards,
Srdjan

**Comment by josiahking** [comment]
Hello @srdjanRakic thanks for the feedback, at the moment am still unable to install this package via npm. Could this be fixed.
Cheers.

**Comment by srdjanRakic** [comment]
Hello @josiahking , can you try installing it using [yarn](https://yarnpkg.com/getting-started/install)?

**Comment by josiahking** [comment]
Hi @srdjanRakic I was able to install using npm pack, then after getting the file, i installed using npm install without error.
The example also worked. Thanks alot.
