### ISSUE TITLE
Can't find variable localStorage

### ISSUE THREAD

**Issue by josiahking** [inplayer-org/inplayer.js#569]
## EXPECTED BEHAVIOR

_What's the behavior you're expecting to see?_
The request return the data rather than storing it, or at least provide multiple storage options.

## ACTUAL BEHAVIOR

_What's actually happening instead?_
Processing data to store in localStorage

## STEPS TO REPRODUCE

_Please provide some simple steps to reproduce the issue._
Inplayer.Account.signIn method called

## SUGGESTED SOLUTION

_Do you have any feedback on how this problem should be solved?_

**Comment by srdjanRakic** [comment]
Hi @josiahking, we have fixed the issue and published a new 3.3.0 version of the library.

Regards,
Srdjan

**Comment by josiahking** [comment]
Hi @srdjanRakic thanks, the update worked as expected.
